#https://github.com/sudar/Arduino-Makefile/releases
#https://www.mertl-research.at/ceonwiki/doku.php?id=coding:arduino:devenv_build_process
BOARD_TAG = uno
ARDUINO_PORT = /dev/ttyACM0
ARDUINO_LIBS = 
ARDUINO_DIR = /home/timc/arduino-source/arduino-1.8.13
AVR_TOOLS_DIR = /usr
include /home/timc/arduino-make/Arduino-Makefile-1.6.0/Arduino.mk

