#https://github.com/sudar/Arduino-Makefile/releases
#https://www.mertl-research.at/ceonwiki/doku.php?id=coding:arduino:devenv_build_process
#sub board list:
#ARDUINO_QUIET=1 make show_submenu|grep -i pro
BOARD_TAG = pro
BOARD_SUB = 16MHzatmega328
ARDUINO_PORT = /dev/ttyUSB0
ARDUINO_LIBS = 
ARDUINO_DIR = /home/timc/arduino-source/arduino-1.8.13
AVR_TOOLS_DIR = /
include /home/timc/arduino-make/Arduino-Makefile-1.6.0/Arduino.mk

